### ISSUE TITLE
avifile is out of date

### ISSUE THREAD

**Issue by EFDLuser** [OpenPIV/openpiv-spatial-analysis-toolbox#19]
Hi there. 
We are using Matlab 2017b and the function to save movie in your program, 'avifile', is not in Matlab anymore. Can you please update the code using 'videowriter'?
Thank you.

**Comment by alexlib** [comment]
@EFDLuser I'd like to, but since I do not have an access to this version of Matlab, please suggest a patch or pull request and we'll gladly merge it. Please make sure to create a separate branch called MatlabR2017b - our main problem is to maintain various Matlab versions.

**Comment by alexlib** [comment]
solved in #24
