### ISSUE TITLE
inconsistent definition

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-spatial-analysis-toolbox#23]
https://github.com/OpenPIV/openpiv-spatial-analysis-toolbox/blob/516385ecc087582ec0b9d35c56e6d4b4e6273afb/spatialbox/spatialbox.m#L199

@roigurka pointed out that this definition is inconsistent with the book

![unnamed](https://user-images.githubusercontent.com/747110/47678070-8620b500-dbc9-11e8-91a2-0a1eeb53730b.jpg)

**Comment by alexlib** [comment]
it's suggested to change to 

`handles.diss = handles.diss + 2*(dudx).^2 + 2*(dvdy).^2 + (dudy + dvdx).^2;`

**Comment by roigurka** [comment]
Thanks to Xia (jxia27@uwo.ca), who identified it. We can keep it as factored by 2 for the dissipation.

**Comment by alexlib** [comment]
> Thanks to Xia ([jxia27@uwo.ca](mailto:jxia27@uwo.ca)), who identified it. We can keep it as factored by 2 for the dissipation.

- I do not understand, sorry - to change it as suggested or to change it to something else?

**Comment by roigurka** [comment]
Change it as suggested. It does not matter if there is a 2 factor or not, as long as the normal stresses are 2 times higher than the shear..so the change you made is fine, Thanks, Roi

**Comment by alexlib** [comment]
solved in #25
