### ISSUE TITLE
The Spatialbox was choosing wrong regions, rows and columns 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-spatial-analysis-toolbox#4]
Please, review the Spatial toolbox from my repository for the bug fixes

**Comment by akkupant** [comment]
Hello. I am getting the same issue. The region I get the data for  is different from the region i select.
 Is it fixed in the Python version?
best regards
Anurag

**Comment by alexlib** [comment]
> Hello. I am getting the same issue. The region I get the data for is different from the region i select. Is it fixed in the Python version? best regards Anurag

Please show a sequence of operations that lead to the bug. We hardly support this software, the Python version is not yet ready at this level of GUI, it's only a Jupyter notebook with commands https://github.com/alexlib/pivpy

**Comment by akkupant** [comment]
As it can be observed from the attached image, I have chosen a region to plot the data along its rows. The y range should be from 0.068 to 0.1 (approximately), according to the selection.
However, as can be seen from the legend, the data is plotted with y ranging from 0.04-0.068, which is incorrect.
Thanks for the prompt reply.
best regards
Anurag



![OpenPIVSpatial](https://github.com/OpenPIV/openpiv-spatial-analysis-toolbox/assets/166389050/8e61de4c-c63c-4b43-82c3-0b78c43e34c9)

**Comment by alexlib** [comment]
choose columns at the bottom instead of rows
________________________________

**Comment by akkupant** [comment]
As can be seen again, the  y range in the plot does not lie inside the selected region. I'm sorry if I'm mistaken anywhere but I wanted to be able to plot the variation of u along x or y direction.
![OpenPIVSpatial3](https://github.com/OpenPIV/openpiv-spatial-analysis-toolbox/assets/166389050/13897b0b-d442-4b52-8d2e-c3c94137bea0)

**Comment by akkupant** [comment]
Thanks again!
